import numpy as np
import copy
# print(np.ndarray([1,2,3,4]))
print(np.array([1,2,3,4]))
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)

# a = np.array([1, 'm', [2, 3, 4]], dtype=object)
# print(a.dtype)
# b = copy.deepcopy(a)
b = a[:][:]
b[1][1] = 9
print(a)
print(b)

print(a.shape)
print(a.dtype)

print(a.strides)
print(a.flags)
print(a.data)
print(a.ndim)
print(a.itemsize)
print(a.nbytes)
print(a.base)
print(a.T)
print(a.real)
print(a.imag)
for i in a.flat:
    print(i)
print(a.__array_interface__)
print(a.item((1,2)))
print(a.tolist())
print(a.tobytes())
print(a.astype(float))
arr = np.array([[1,2,3],[0,5,6],[7,8,9]],order='C')

# print(arr.byteswap())
print(a.getfield(dtype=float))
# a.fill(0)
print(a)
print(a.reshape((3,2)))

a.resize((3,3),refcheck=False)
print(a)

# print(arr.shape)
# print(arr)
# arr.squeeze(axis=0)
# print(arr.shape)
# print(arr)
print(arr)
print(arr.take([1,3]))
print(arr.nonzero())
print(arr)
print(np.count_nonzero(arr,axis=1))
print(np.count_nonzero(arr,axis=1,keepdims=True))
print(np.empty((2,2)))
print(np.arange(4).reshape(2,2))
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concat((a,b))
print(c)

x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])
# xy = np.concatenate((x,y),axis=1)
# print(xy)
print(x.shape)
newx = x[:,:,np.newaxis]
print(newx)
print(newx.shape)
print("---")
print(y.shape)
newy = y[np.newaxis,:,:]
print(newy)
print(newy.shape)

print("---")
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])
print(y.shape)
newy = np.expand_dims(a,axis=1)
# print(newy.reshape(2,2))
print(newy.shape)
print(x[-1:])
arr1 = np.arange(100)
print(arr1[arr1>50])
five_up = (arr1 > 5) | (arr1 == 5)
print(arr1[five_up])

table_of_5 = np.nonzero(arr1 % 5 == 0)
print(table_of_5)