import time
import tkinter as tk
import turtle as tr

# s = tr.getscreen()

tr.bgcolor("blue")
tr.title("My Turtle Program")
t = tr.Turtle()
# t1 = tr.Turtle()
# t1.shape("square")
t.shape("turtle")
t.fillcolor("red")
t.left(90)
# t.speed(1)
t.forward(100)
# t.left(90)
# # t1.left(90)
# t.backward(100)
# t.goto(100,100)
# # t1.forward(90)
# # t.clear()
# t.undo()
# t.home()
# t.stamp()
# t.speed(7)
# t.color("green", "blue")
# t.pensize(5)
# t.goto(200,200)
# t.circle(20)
# t.dot(40)

# t.shapesize(1,5,10)
# time.sleep(1)
# t.shapesize(10,5,1)
# time.sleep(1)
# t.shapesize(1,10,5)
# time.sleep(1)
# t.shapesize(10,1,5)
# t.reset()
tk.mainloop()