# Generated by Django 5.1.6 on 2025-02-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pediatrics', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
