# Generated by Django 5.1.6 on 2025-02-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pediatrics', '0003_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baby',
            new_name='Baby_Server',
        ),
    ]
