# Generated by Django 5.1.6 on 2025-02-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatrics', '0004_rename_baby_baby_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('delivery', models.CharField(max_length=30)),
                ('neonatal_status', models.CharField(max_length=30)),
                ('birth_weight', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
                ('head_circumference', models.CharField(max_length=20)),
                ('chest_circumference', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=3)),
                ('remarks', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('mother_blood_group', models.CharField(max_length=3)),
                ('father_name', models.CharField(max_length=30)),
                ('father_blood_group', models.CharField(max_length=3)),
                ('details_of_siblings', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Baby_Server',
        ),
    ]
